- name: Install network-manager-applet
  pacman:
    name: network-manager-applet
    state: present
  become: yes
  tags:
    - vpn

- name: Install openvpn
  pacman:
    name: openvpn
    state: present
  become: yes
  tags:
    - vpn

- name: Install networkmanager-openvpn
  pacman:
    name: networkmanager-openvpn
    state: present
  become: yes
  tags:
    - vpn

- name: Ensure .vpn directory exists.
  file:
    dest: "{{ dest_key_vpn | dirname }}"
    mode: 0700
    state: directory
  tags:
    - vpn
- name: Install vpn key 安装秘钥
  copy:
    src: "{{ source_key_vpn }}"
    dest: "{{ dest_key_vpn }}"
    mode: 0600
  tags:
    - vpn
