- name: 备份 Ubuntu 镜像文件 sources.list
  become: true
  ansible.builtin.command:
    cmd: cp /etc/apt/sources.list /etc/apt/sources.list.backup
  when:
    - ansible_distribution == "Ubuntu"
  tags: sources_backup

- name: 替换 Ubuntu 镜像文件 sources.list 为 清华源
  become: true
  ansible.builtin.copy:
    src: sources.list.mirror
    dest: /etc/apt/sources.list
  when: ansible_distribution == "Ubuntu"
  tags: sources_update
