- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'

- name: Install timeshift
  pacman:
    name: timeshift
    state: present
  become: yes

- name: Install timeshift-autosnap
  aur:
    name: timeshift-autosnap
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder
    
- name: Install grub-btrfs
  pacman:
    name: grub-btrfs
    state: present
  become: yes

- name: Install duf
  pacman:
    name: duf
    state: present
  become: yes

- name: Install inotify-tools for grub-btrfsd service
  pacman:
    name: inotify-tools
    state: present
  become: yes

- name: Install floorp-bin
  aur:
    name: floorp-bin
    use: makepkg
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - browser
    - browser.floorp

- name: Install gnome-browser-connector
  pacman:
    name: gnome-browser-connector
    state: present
  become: yes
  tags:
    - gnome

- name: Install gnome-shell-extension-pop-shell
  kewlfft.aur.aur:
    use: yay
    name:
      - gnome-shell-extension-pop-shell 
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - gnome

- name: Install dconf-editor
  pacman:
    name: dconf-editor
    state: present
  become: yes
  tags:
    - gnome

- name: Install neovim
  pacman:
    name: neovim
    state: present
  become: yes
  tags:
    - basic

- name: Install neofetch
  pacman:
    name: neofetch
    state: present
  become: yes
  tags:
    - basic

- name: Install gnome-shell-extension-blur-my-shell 
  kewlfft.aur.aur:
    use: yay
    name:
      - gnome-shell-extension-blur-my-shell 
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - gnome

- name: Install gnome-shell-extensions
  pacman:
    name: gnome-shell-extensions
    state: present
  become: yes
  tags:
    - gnome

- name: Install gnome-shell-extension-space-bar-git
  kewlfft.aur.aur:
    use: yay
    name:
      - gnome-shell-extension-space-bar
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - gnome

- name: Install gnome-shell-extension-vitals
  kewlfft.aur.aur:
    use: yay
    name:
      - gnome-shell-extension-vitals
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - gnome

- name: Install gnome-shell-extension-top-bar-organizer
  kewlfft.aur.aur:
    use: yay
    name:
      - gnome-shell-extension-top-bar-organizer
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - gnome

- name: Install gnome-shell-extension-kimpanel
  kewlfft.aur.aur:
    use: yay
    name:
      - gnome-shell-extension-kimpanel
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - gnome

- name: Install vim-fcitx
  kewlfft.aur.aur:
    use: yay
    name:
      - vim-fcitx
    state: present
  become: yes
  become_user: aur_builder
  tags:
    - neovim
